on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  URL_TO_CURL: "http://demo.codegiant.io" 

jobs:
  curl_request:
    name: Curl Request
    runs-on: ubuntu-latest


    steps:
      - name: curl
        run: curl -I $URL_TO_CURL
